### ISSUE TITLE
Implementing TDD in project

### ISSUE THREAD

**Issue by luife69** [angelahe/dream2do#18]

**Comment by luife69** [comment]
TDD workspace and protocol
Test protocol

Write stubs
Write fail Tests
Write pass tests
Manage Coverage% goals

**Test types**
Tests for Loading
Tests for re-sizing
Tests for Device/ screen types
Tests for component functionality

**Comment by Matt-Fisherrr** [comment]
matt showed me the coverage report and we are already working TDD
