### ISSUE TITLE
learn Git functionality - Branching form main convention

### ISSUE THREAD

**Issue by luife69** [angelahe/dream2do#19]

**Comment by luife69** [comment]
Resolve merge conflict of monday morning

**Comment by luife69** [comment]
Define main branch and development branchs practise

**Comment by Matt-Fisherrr** [comment]
agreement was reached as to protocols for branch cration and use, all merges to main are to be approved by pair angela+ Roger until we feel more confortable

All user shoud pull copy of main to temporary work branch and work on that

**Comment by Matt-Fisherrr** [comment]
done
